[package]
name = "mere_asset"
version = "0.1.0"
edition = "2024"

[build-dependencies]
anyhow = "1.0.102"
blake3 = "1.8.3"
gltf = { version = "1.4.1", features = ["KHR_lights_punctual"] }
mere_log = { version = "0.1.0", path = "../mere_log" }
mere_mesh = { version = "0.1.0", path = "../mere_mesh" }
meshopt = "0.6.2"

[dependencies]
gltf = { version = "1.4.1", features = ["KHR_lights_punctual"] }
meshopt = "0.6.2"
