[package]
name = "mere"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "3"
members = ["mere_asset", "mere_asset/common", "mere_common", "mere_log", "mere_math", "mere_mesh", "mere_render"]

[workspace.dependencies]
anyhow = "1.0.102"
bytemuck = { version = "1.25.0", features = ["derive"] }
meshopt = "0.6.2"
wgpu = { version = "29.0.1", default-features = false, features = ["std", "parking_lot", "dx12", "gles", "vulkan", "wgsl"] }

[dependencies]
mere_asset = { version = "0.1.0", path = "mere_asset" }
mere_log = { version = "0.1.0", path = "mere_log" }
mere_math = { version = "0.1.0", path = "mere_math" }
mere_render = { version = "0.1.0", path = "mere_render" }
