[package]
name = "mere_render"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
bytemuck.workspace = true
egui.workspace = true
egui-wgpu.workspace = true
egui-winit.workspace = true
egui_plot = "0.35.0"
mere_asset = { version = "0.1.0", path = "../mere_asset" }
mere_log = { version = "0.1.0", path = "../mere_log" }
mere_math = { version = "0.1.0", path = "../mere_math" }
mere_mesh = { version = "0.1.0", path = "../mere_mesh" }
rand = "0.10.1"
wgpu.workspace = true
winit = "0.30.13"
