[package]
name = "mere_mesh"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
bytemuck.workspace = true
gltf.workspace = true
half = "2.7.1"
itertools.workspace = true
mere_log = { version = "0.1.0", path = "../mere_log" }
mere_math = { version = "0.1.0", path = "../mere_math" }
meshopt.workspace = true
metis.workspace = true
wgpu.workspace = true
